language: node_js
node_js: node

branches:
  only:
  - master
  - beta
  - polymer-2
stages:
  - test
  - name: deploy
    if: branch = master

env:
  - TEST=test-build
  - TEST=test-local
  - TEST=test:chrome:26
  - TEST=test:chrome:30
  - TEST=test:chrome:latest
  - TEST=test:firefox:quantum
  - TEST=test:firefox:latest
  - TEST=test:edge:16
  - TEST=test:edge:latest

before_install:
- openssl aes-256-cbc -K $encrypted_f2a12e06bc88_key -iv $encrypted_f2a12e06bc88_iv
  -in test/UI/secrets.js.enc -out test/UI/secrets.js -d
- npm install gulp -g
install:
- yarn
script: sh ./scripts/pretest.sh && yarn run $TEST || yarn run $TEST

jobs:
  include:
    - stage: deploy
      script: sh ./scripts/deploy.sh
      env: TEST=none

notifications:
  email:
    on_success: change
    on_failure: change
addons:
  browserstack:
    username: "sanderronde1"
    access_key:
      secure: uKeeDZKoavvWTT7CcuHfodSItQKf7ot/TLtkhP9HWXhN2ad45ELjZ4p4b+U766vsML7TH/vUypFj9egguOlTG1OXx2jMBrT2vqz+nMWNEVFj8zZ6Lfj6bPaJD4eqAqrKby9HWX8ZweDG9+WgDlABKZ4kw08yVK98KrVHhgpgTLYVj066LOlzTG5XcvNj3nu/+Ld3LetNuKBw4/s6y+n+dBsYm0v7PWERQOWDb4vpD4Gg/J+lZXjJCbZg6OQV2F2Fzg8pH+17d8r3do4/TavI/VgdM0vdbvFHTISlaoh7qv2BKinhTvQTUXhjzxZApnUwtXY+XzM3LPuD0Y8/tWqUxVKu2CEbTDXHk8rbkxdeSmGjhdWsnkNyRg8U30MYUtS+WS+jz8n9IKxe5QOXy6cY0l0YlWobzT+xHBlpKPktur8r3Q9h0lVEr6BYaWe0r2Zz34hqQwkQj8bivheOSBoRXTqRlz3HYJAuetstNj1U96Xov0+ydJQK3CPqLliI1bCboQ05a7vBEOQ5M65BHNQ/ZUUDxZKRmj9dAIsEgqYAguX+dB3vebVeZGAvqtxFsEX0Z0YUbkHGDMHf1948hucot4ACuXQIXgPzgYI6347M3JxGyjrkFFbi9M7Qo7/ffp8vA3cHRtuqWecJj7tkD6Cb/I7cgyMAQDx1rUZmfZr0W9I=