language: node_js
node_js: node

branches:
  only:
  - master
  - beta
  - polymer-2
stages:
  - test
  - name: deploy website
    if: branch = master

env:
  - TEST=test-build
  - TEST=test-local
  - TEST=test:chrome:26
  - TEST=test:chrome:30
  - TEST=test:chrome:latest
  - TEST=test:firefox:quantum
  - TEST=test:firefox:latest
  - TEST=test:edge:16
  - TEST=test:edge:latest

before_install:
- openssl aes-256-cbc -K $encrypted_f2a12e06bc88_key -iv $encrypted_f2a12e06bc88_iv
  -in test/UI/secrets.js.enc -out test/UI/secrets.js -d
- npm install gulp -g
install:
- yarn
script: sh ./scripts/pretest.sh && yarn run $TEST || yarn run $TEST

jobs:
  include:
    - stage: deploy website
      script: sh ./scripts/deploy-website.sh
      env: TEST=none

notifications:
  email:
    on_success: change
    on_failure: change