language: node_js
node_js: node
branches:
  only:
  - master
  - beta
before_install:
- openssl aes-256-cbc -K $encrypted_f2a12e06bc88_key -iv $encrypted_f2a12e06bc88_iv
  -in test/secrets.js.enc -out test/secrets.js -d
- npm install grunt -g
install:
- npm install
script: sh ./build.sh
notifications:
  email:
    on_success: change
    on_failure: change
