language: node_js
node_js: node
branches:
  only:
  - master
  - beta
before_install:
- openssl aes-256-cbc -K $encrypted_2f49f885e77e_key -iv $encrypted_2f49f885e77e_iv
  -in test/UI/secrets.js.enc -out test/UI/secrets.js -d
- npm install grunt -g
install:
- npm install
script: sh ./build.sh
notifications:
  email:
    on_success: change
    on_failure: change
addons:
  browserstack:
    username: sanderronde1
    access_key:
      secure: secure: L8GIXKNcj4i5LJyvgLI3xRmupxt5bFRKbkYZacfh6rPeRAZ62FqvXCTyvpRoCN+KDP8q6ib+13ejL9kF4YyPXN1a54esv3ivKWs5QPFL8aKcKaSfkFQ/DjKamIb+r8+TB4gh02ST0IwtV46YYHEQfT8YXjmB1l/gTKS0CX8l6xgf8sCZhLEeCxf3+LQ7SoG3RAdDWhgHdHa2eJoACsj7ZfZf18BKcH3Nf4GmgosLKGYGZhkClUriun7KfGzU5z5nOpWW45ZnnFKAPsMxFk7KfWsAOL+TmoYx4PypRgCDlRz7M3ciWrrkCMkZ4tFezYwzUYFd0YXm1YwaEqe4KLLnorswRaCDfAIFISIp/IlaR1V5Rp7Hje0eTyVggmCr5UFMpy9B0UXJb9kpK9r2mUIo5D4rurH8VwpAwysU+Aya2R/H92uuUVWVH423UxGqaU//vSqXG6wuD/xxivJ7uvllmpAI9ylNF93dd4dNMT3Fft4RTCkw75U5c7lHAOYl6b+Xk7+RiUxZkvF/k5wFBw3V4KuoeofeJGiBoqnTOuix4oEdJp83MvfmDfK0+B60lWRdUFiu8VuuFHmRrWbz+uNkbxxTAZZOXtdyJ+m+Y+WrKa4l8nX/YbkXpF9ohhsfcbhFT4OKHb4JDUVMZxIsol2zij28wG5ZP8eIt1rTNUCYGLs=